name: front build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      ACTOR: ${{ github.actor }}

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          back:
            - 'back/**'
          front:
            - 'front/**'
          db:
            - 'db/**'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push front
      if: steps.changes.outputs.front == 'true'
      uses: docker/build-push-action@v4
      with:
        context: front
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_NAME }}-front:1.0.0

    - name: Build and push back
      if: steps.changes.outputs.back == 'true'
      uses: docker/build-push-action@v4
      with:
        context: back
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_NAME }}-back:1.0.0

    - name: Build and push db
      if: steps.changes.outputs.db == 'true'
      uses: docker/build-push-action@v4
      with:
        context: db
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_NAME }}-db:1.0.0

  